export const ROUTER = {
    TEST: '/test',
    HOME: '/',
    DESTINATION: '/destination',
    SUBDES: '/sub-des',
    ARTICLE: '/article',
    ABOUT: '/about',
    GALLERY: '/gallery',
    CONTACT: '/contact',
    SEARCH: '/search',
    ADMIN: '/admin',
    ADDASHBOARD: '/admin/dashboard',
    ADPOST: '/admin/posts',
    ADCATEGORY: '/admin/category',
    ADLOGIN: '/admin/login',
    CREATEPOST: '/admin/posts/create',
    SKINTYPE: '/skintype',
    ADSUBCATE: '/admin/sub-category',
    NOTFOUND: '/notfound',
    TESTREVIEW: '/test_review',
    INGREDIENT: '/ingredient',
    INGREDIENTDETAIL: '/ingredient/detail',
    TESTPOST: '/test_post',
    ADINGREDIENT: '/admin/skincare-ingredients'

}