export const ROUTER = {
    TEST: '/test',
    HOME: '/',
    DESTINATION: '/destination',
    SUBDES: '/sub-des',
    ARTICLE: '/article',
    ABOUT: '/about',
    GALLERY: '/gallery',
    CONTACT: '/contact',
    SEARCH: '/search',
    ADMIN: '/admin',
    ADDASHBOARD: '/admin/dashboard',
    ADPOST: '/admin/post',
    ADCATEGORY: '/admin/category',
    ADLOGIN: '/admin/login',
    CREATEPOST: '/admin/create_post',
    SKINTYPE: '/skintype',
    ADSUBCATE: '/admin/sub-category',
    NOTFOUND: '/notfound',
    TESTREVIEW: '/test_review'
}